apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
        - name: microservice1
          image: your-docker-username/microservice1:latest  # Mettez à jour avec votre nom d'utilisateur Docker
          ports:
            - containerPort: 3000
