apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice2
  template:
    metadata:
      labels:
        app: microservice2
    spec:
      containers:
        - name: microservice2
          image: your-docker-username/microservice2:latest  # Mettez à jour avec votre nom d'utilisateur Docker
          ports:
            - containerPort: 3001
